baseURL = 'https://blog.wolfarmoon.dev'
languageCode = 'en-us'
title = "Wolfarmoon"
theme = "enervoid"

[menus]
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 10

  [[menus.main]]
    name = 'Personal'
    pageRef = '/personal'
    weight = 20


[params]
  avatar = "https://wolfarmoon.dev/favicon.ico"

  [[params.socials]]
      link = "https://codeberg.org/wolfarmoon"
      icon = "devicon-forgejo-plain"
    [[params.socials]]
      link = "https://wolfarmoon.itch.io/"
      icon = "fa-brands fa-itch-io" 

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['$$','$$'], ['\\[','\\]']]
        inline = [['$','$'], ['\\(','\\)']]

    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[markup.highlight]
  noClasses = true
  codeFences = true
  guessSyntax = true
  tabWidth = 4
  style = "monokai"
